feat: add positive and negative tests for MPT inclusion
axiom-crypto/axiom-eth pull request #4
Opened 2023-06-05 23:39 UTC by MonkeyKing-1

2023-06-05 23:44 UTC, yi-sun requested changes

2023-06-05 23:44 UTC, yi-sun commented on scripts/input_gen/INFURA_ID
> +0c602f5267ba478eb5b101f1f1b335d4
Remove this private file.

2023-06-05 23:44 UTC, yi-sun commented on src/mpt/tests/mpt_tests.rs
> +// fn get_test_circuit(network: Network, num_slots: usize) -> EthBlockStorageCircuit {
Is this intentionally commented out?  If so, remove

2023-06-05 23:44 UTC, yi-sun commented on src/mpt/tests/mpt_tests.rs
> +//"scripts/input_gen/noninclusion_extension_pf.json"
Clean up all comments below too

2023-06-05 23:47 UTC, MonkeyKing-1 commented on scripts/input_gen/INFURA_ID
> +0c602f5267ba478eb5b101f1f1b335d4
Done

2023-06-06 13:38 UTC, MonkeyKing-1 commented
Comments and key are both removed now

2023-06-07 06:42 UTC, yi-sun commented on src/mpt/tests/mpt_tests.rs
> +    // std::env::set_var("ETH_CONFIG_PARAMS", serde_json::to_string(&params).unwrap());
Remove extraneous comments

2023-06-07 06:48 UTC, yi-sun approved these changes
Fine to merge after removing the last extraneous comment.

2023-07-26 00:44 UTC, closed without merging